GET http://localhost:9999/api/posts

###

POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 2,
  "content": "Last Post number n n"
}

###

DELETE http://localhost:9999/api/posts/4

###

GET http://localhost:9999/api/posts/4